name: Deployment Pipeline

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    types: ["opened", "synchronize"]

jobs:
  avoid_redundancy:
    runs-on: ubuntu-18.04
    steps:
      - name: Cancel Workflow Action
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: dist
          path: dist

  test:
    needs: [build]
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Download a Build Artifact
        uses: actions/download-artifact@v3.0.2
        with:
          name: dist
          path: dist
      - name: Test
        run: npm run test

  deploy:
    needs: [test]
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Last build to check if it's a push
        if: ${{ github.event-name == 'push' }}
        run: npm run build
